### ISSUE TITLE
Update npm packages based on the Dependabot alert

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_theme#156]
The weekly Dependabot alerts have been patiently pointing out the npm packages that have security updates available.  We are not using these packages in the backend.   So as discussed in Standup already, these vulnerabilities are less severe for us.  But should be actioned at some point just in case.

@cjstevens78 @finnlewis @paulpopus @willguv

**Comment by paulpopus** [comment]
I don't have "admin" or the right permissions on this repo like I do on the docs repo, so I can't see the alerts. Usually I'm on top of them. Happy to take a look if you or someone else can give me the perms, the bot usually opens a PR for you! @Adnan-cds

**Comment by Adnan-cds** [comment]
> Usually I'm on top of them. Happy to take a look if you or someone else can give me the perms

Ah... I always thought you have write access to this repo.  Done now. @paulpopus

**Comment by paulpopus** [comment]
@Adnan-cds I still don't see the dependabot alerts under the Security tab like I do in the docs repo. Unless I'm not meant to?

**Comment by Adnan-cds** [comment]
> Unless I'm not meant to?

You are right.  Just having write access doesn't activate the Dependabot alerts.  I have had to explicitly add you to the list of people and teams who will get these alerts. @paulpopus

**Comment by paulpopus** [comment]
Thanks I'll get on them!

**Comment by Adnan-cds** [comment]
Thanks Paul :)  Please do assign this issue to yourself when you are ready. @paulpopus

**Comment by paulpopus** [comment]
Hi @Adnan-cds 
So I've solved some of the security issues, some outstanding things.
[PR](https://github.com/localgovdrupal/localgov_theme/pull/158) for you or someone to review, I've removed `gulp-notify` `gulp-plumber` and `gulp-version-append` because they were unused modules, some which now used deprecated dependencies and removed them from the Gulpfile (their functionality was not used). I need this reviewed, issues may still be outstanding but it will make them easier to resolve.

For [this issue](https://github.com/localgovdrupal/localgov_theme/security/dependabot/package-lock.json/sync-exec/open) I want to Dismiss it as "Vulnerable code is not used" because we don't run Node.js apps and in the Mocha tests we're using the correct child_process.execSync function.

**Comment by Adnan-cds** [comment]
> I want to Dismiss it as "Vulnerable code is not used" 

That'll do.  Thanks :)

**Comment by Adnan-cds** [comment]
Let's wait for next weeks Dependabot report before closing this ticket.

**Comment by paulpopus** [comment]
I think it's good to close now, I'll get on any alerts if they come up.
