### ISSUE TITLE
Clean up Twig template files and related css and preprocess functions

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#18]
I suggest the theme should only contain a minimal set of template files. Modules can contain basic templates for the page elements they provide; e.g. node, paragraphs, etc. It then becomes the responsibility of child themes to override templates.

With this in mind, what sort of classes do we want to support? The theme uses elements from Bootstrap. Do we want to support Bootstrap layout classes not just in the theme but also in module template files?

**Comment by andybroomfield** [comment]
I think the only requirement is the bootstrap grid for layout in the template files. 
A compromise would be to include the grid css as a library in localgov_core and then unset it if the theme is present (or make it a checkbox option in settings) so that bootstrap themes don't get the grid, but non bootstrap ones do.

**Comment by finnlewis** [comment]
Discussing this in sprint planning, probably good to discuss and review with @stephen-cox @cjstevens78  initially to confirm who's doing what.
