### ISSUE TITLE
Resolve SASS linting errors

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#39]
When running `gulp build` we lint the `assets/scss` dir which shows lots of errors. If we're going to lint the SASS let's ensure that we conform with the the linting rules. 
We should also confirm that the linting rules are Drupal standards compliant

**Comment by danchamp** [comment]
A lot of the errors are due to indentation, use of px as a unit (it's not in the .stylelintrc unit-whitelist), and declaration of colours using hex values (disallowed in

**Comment by danchamp** [comment]
The current stylelint rules are tight, and a lot of the errors are due to these two rules:

1. No hex colour values allowed:
https://github.com/localgovdrupal/localgov_theme/blob/c77a839db0f9913f65cfcf288fe3f0703222c16c/.stylelintrc#L19

2. px not in the unit whitelist:
https://github.com/localgovdrupal/localgov_theme/blob/c77a839db0f9913f65cfcf288fe3f0703222c16c/.stylelintrc#L26

[Drupal CSS guidelines](https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines#s-properties) allow for use of px on this basis: "Use rem units preceded by px units for a safe fallback, unless it creates an undesired effect."

And colours in any valid format: "When hex values are used for colors, use lowercase and, if possible, the shorthand syntax, e.g. #aaa. Colors may be expressed with any valid CSS value, such as hex value, color keyword, rgb() or rgba()."

All of the remainder are whitespace / indentation issues, apart from 2 duplicate selector warnings.

Suggest we edit those two lint rules accordingly, and fix the remaining issues.

**Comment by cjstevens78** [comment]
We use a mixin that converts a supplied px value into rem with a px fallback, the lint rule to flag the use of px is to pick up on any direct usage of px and steer the dev in the direction of implementing it using the mixin. For the hex values, all colour declarations should be made in the _variables.scss file as a hex value and declared throughout by the variable name not the hex value. The linter will flag any instances of a hex value being used directly and to resolve this it should be replaced with a variable.

**Comment by danchamp** [comment]
Thanks @cjstevens78 it makes more sense now, and I can make a start fixing some of the errors.
