### ISSUE TITLE
Design Dave feedback on LocalGov Drupal theme

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#64]
@clearspotmedia and @cjstevens78 here's a card for you to discuss minor tweaks to the LGD default theme

**Comment by clearspotmedia** [comment]
@cjstevens78 Here are some initial observations.
@willguv There's likely to be more when you've added directory content / more content so please let me know when that is in place.

Develop the font awesome icon page to show all the icons we have used


**Feedback on 
https://localgovdrupal.agile.coop/**

1) Main navigation has an id **id="menu-purejs”**.
This is a legacy id from the old design system that used the vanilla javascript rather than Bootstrap JS.

I can see there are some styles assigned for this ID but we may want to re-name the ID or convert it to a class with a new name as the ‘pure-JS’ may be misleading.


2) Main navigation services dropdown menu toggle has an ID “js-drop-toggle”, this is a legacy class from the old design system pre Bootstrap JS and is not needed.


3) The lower footer at the bottom of the page has a class of "nav-vanilla”,  this is a legacy class  from the old design system pre Bootstrap JS, looks like it can be removed completely.


4) The dark grey footer has a class of “bg-carbon” which is a Croydon specific colour variable, please see the Gray Variables in the LocalGov Theme PDF page 9. Not sure if these greys have been implemented in the theme yet.


5) The work we did on improving margins above headings (h2-h6) is missing
https://localgovdrupal.agile.coop/adult-health-and-social-care/support-your-home/meals-wheels


6) Templates have full width page content (overly long line lengths not good for accessibility) which we don’t have in the croydon design system, pages usually include a sidebar to prevent this even if left empty.

https://localgovdrupal.agile.coop/adult-health-and-social-care/support-your-home/meals-wheels

Semantic templates reference:
https://new.croydon.gov.uk/design-and-content-guidelines/resources/semantic-templates

7) The services menu (main navigation expandable) white background pushes outside of the site max width.

8) Nested ‘container-fluid site-max’ classes are causing layout problems with indentations.


There should only be one “container-fluid site-max” class on the page wrapper, then all other content should be placed in divs with the class "row" to follow the Bootstrap markup of container > row > col.

https://localgovdrupal.agile.coop/adult-health-and-social-care
The following elements have the nested 'container-fluid site-max' classes:

• The x3 CTA buttons (aria-label="Section Navigation")

• The hub list links container (<section class="container-fluid site-max servicehub--more”>)

• The block that contains ‘contact this service’ and ‘popular topics’ 
(<div class="container-fluid site-max”>)


9) Step by step contents page runs full width which is different to the Croydon design system:
https://localgovdrupal.agile.coop/adult-health-and-social-care/step-by-step/request-support-adult-step-step

REF: https://new.croydon.gov.uk/adult-health-and-social-care/request-support-adult-step-step

10) Step by step column widths are different to the croydon design system:

https://localgovdrupal.agile.coop/adult-health-and-social-care/step-by-step/request-support-adult-step-step/find-out-what-support-we

REF: https://lbcdsanetcallp.blob.core.windows.net/html/semantic-templates/step-by-step.html

**Comment by cjstevens78** [comment]
Changes for this are in branch origin/feature/64-theme-design-feedback
PR: https://github.com/localgovdrupal/localgov_theme/pull/74

Only thing to note is the 'missing sidebar' issues - needs discussion as im not sure how this is intended to work for localgov - also ive seen @Adnan-cds is doing something related to this area at the moment

**Comment by finnlewis** [comment]
Moving to Sprint 10 for review, planning

**Comment by cjstevens78** [comment]
This is done - closing
